CREATE TABLE IF NOT EXISTS regras_rotas (
 id INT PRIMARY KEY AUTO_INCREMENT,
 numero_rota INT NOT NULL,
 operacao VARCHAR(80) NOT NULL DEFAULT 'PADRAO',
 intensidade VARCHAR(30) NOT NULL,
 dias_ciclo INT NOT NULL,
 motorista_fixo_id INT NULL,
 atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY rota_operacao(numero_rota, operacao)
);
CREATE TABLE IF NOT EXISTS motoristas (
 id INT PRIMARY KEY AUTO_INCREMENT,
 nome VARCHAR(160) NOT NULL,
 dedicado_bonini BOOLEAN NOT NULL DEFAULT FALSE,
 ativo BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS historico_alteracoes (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 entidade VARCHAR(80) NOT NULL,
 entidade_id VARCHAR(80) NOT NULL,
 descricao TEXT NOT NULL,
 criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
