import {useState} from 'react';
import {Alert,Box,Button,Chip,Container,Divider,Drawer,FormControlLabel,MenuItem,Paper,Select,Stack,Switch,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography,LinearProgress} from '@mui/material';
import readXlsxFile from 'read-excel-file';
import SysempPanel,{useSysemp} from './SysempPanel';
type Route={id:number;name:string;driver:string;intensity:string;days:number;pb:number;truck:number;orders:number;km:number;fixed:boolean};
const initial:Route[]=[{id:1,name:'Interior / SP',driver:'Ariel',intensity:'Mediana',days:1,pb:31,truck:0,orders:8,km:245,fixed:false},{id:2,name:'Capital / SP',driver:'Fernando',intensity:'Leve',days:1,pb:20,truck:0,orders:6,km:149,fixed:false},{id:3,name:'Passos / MG',driver:'Leandro Vieira',intensity:'Intensa',days:1,pb:19,truck:5,orders:6,km:542,fixed:false},{id:4,name:'Franca / SP',driver:'Leandro Lima',intensity:'Intensa',days:1,pb:38,truck:0,orders:9,km:610,fixed:true},{id:5,name:'Itajubá / MG',driver:'A definir',intensity:'Muito intensa',days:2,pb:46,truck:0,orders:12,km:690,fixed:false},{id:7,name:'Presidente Prudente / SP',driver:'Denis',intensity:'Muito intensa',days:2,pb:35,truck:0,orders:10,km:980,fixed:true},{id:11,name:'Pitangui / MG',driver:'Wilson',intensity:'Muito intensa',days:2,pb:40,truck:0,orders:8,km:1100,fixed:true},{id:12,name:'Resende / RJ',driver:'Renato',intensity:'Muito intensa',days:2,pb:28,truck:0,orders:7,km:720,fixed:true},{id:13,name:'Registro / SP',driver:'A definir',intensity:'Intensa',days:1,pb:23,truck:0,orders:6,km:360,fixed:false}];
const nav=['Visão geral','Pré-rotas','Conferência','Pedidos','Motoristas','Regras','Conexão SYSEMP'];
const tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function clean(raw:string){return raw.split(/[\n;\t]+/).map(x=>x.trim()).filter(Boolean).map(x=>({original:x,clean:x.replace(/[.,\s]/g,'' )}));}
function parseOrders(raw:string){return clean(raw).filter(x=>/^\d+$/.test(x.clean)).map(x=>x.clean)}
export default function App(){
const [page,setPage]=useState(0),[date,setDate]=useState(tomorrow),[routes,setRoutes]=useState(initial),[selected,setSelected]=useState<Route|null>(null),[raw,setRaw]=useState(''),[message,setMessage]=useState(''),[left,setLeft]=useState(''),[right,setRight]=useState(''),[cap,setCap]=useState(43),[truckCap,setTruckCap]=useState(36),[truckMax,setTruckMax]=useState(15);
const [demo,setDemo]=useState(false),[fileName,setFileName]=useState('');
const connection=useSysemp(date);
const [column,setColumn]=useState(''),[columns,setColumns]=useState<string[]>([]),[rows,setRows]=useState<Record<string,unknown>[]>([]);
const parsed=clean(raw),ids=parseOrders(raw),invalid=parsed.filter(x=>!/^\d+$/.test(x.clean)),unique=[...new Set(ids)],result=unique.join(',');
const capacity=(r:Route)=>r.truck>0?truckCap:cap;
async function upload(file:File){try{const values=await readXlsxFile(file);const headers=(values[0]??[]).map((v,i)=>String(v??'').trim()||`Coluna ${i+1}`);if(new Set(headers).size!==headers.length)throw Error('Existem cabeçalhos duplicados. Corrija a planilha antes de importar.');const data:Record<string,unknown>[]=values.slice(1).filter(row=>row.some(v=>v!==null)).map(row=>Object.fromEntries(headers.map((h,i)=>[h,row[i]??''])));if(!data.length)throw Error('A primeira aba não contém uma tabela com cabeçalhos.');setFileName(file.name);setRaw('');setRows(data);setColumns(Object.keys(data[0]));setColumn('');setMessage('Planilha lida. Escolha a coluna de pedidos para continuar.');setPage(3);}catch(e){setMessage(e instanceof Error?e.message:'Erro ao ler planilha');}}
function compare(){const a=new Set(parseOrders(left)),b=new Set(parseOrders(right));return {missing:[...a].filter(x=>!b.has(x)),extra:[...b].filter(x=>!a.has(x)),match:[...a].filter(x=>b.has(x))};}
const comp=compare();
const routeColumn=columns.find(c=>c.trim().toUpperCase()==='ROTA');
const importedRoutes=routeColumn?[...new Set(rows.map(r=>String(r[routeColumn]??'').trim()).filter(Boolean))]:[];

return <Box sx={{display:'flex',minHeight:'100vh'}}><Box component="aside" sx={{width:232,bgcolor:'#173f36',color:'white',p:3,display:{xs:'none',md:'flex'},flexDirection:'column',flexShrink:0}}><Typography variant="h5" fontWeight={850}>ARENA<span style={{color:'#b9e267'}}> /</span></Typography><Typography fontSize={11} sx={{opacity:.65,letterSpacing:2,mt:1,mb:6}}>CENTRAL DE ROTAS</Typography><Stack spacing={1}>{nav.map((n,i)=><Button key={n} onClick={()=>setPage(i)} sx={{justifyContent:'start',py:1.4,color:page===i?'#173f36':'#dce8e0',bgcolor:page===i?'#b9e267':'transparent','&:hover':{bgcolor:page===i?'#b9e267':'#275348'}}}><span style={{width:30,opacity:.6}}>{String(i+1).padStart(2,'0')}</span>{n}</Button>)}</Stack><Box sx={{mt:'auto',pt:8}}><Divider sx={{borderColor:'#ffffff25',mb:2}}/><Typography fontSize={12}>Expedição · Arena Vidros</Typography><Typography fontSize={11} sx={{opacity:.55}}>Planejar. Conferir. Despachar.</Typography></Box></Box>
<Box sx={{flex:1,minWidth:0}}><Box component="header" sx={{px:{xs:2,md:5},py:2,bgcolor:'white',display:'flex',justifyContent:'space-between',alignItems:'center',borderBottom:'1px solid #e4e7df'}}><Typography fontSize={13}>Operação / <b>{nav[page]}</b></Typography><Chip label={demo?"Simulação com exemplos":connection.data?"Consulta SYSEMP carregada":"Aguardando consulta SYSEMP"} size="small" color={demo?"warning":"default"} variant="outlined"/></Box><Container maxWidth="xl" sx={{p:{xs:2,md:5}}}><Box sx={{display:{md:'none'},mb:2}}><Select value={page} onChange={e=>setPage(Number(e.target.value))} fullWidth>{nav.map((n,i)=><MenuItem key={n} value={i}>{n}</MenuItem>)}</Select></Box><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2} mb={3}><Box><Typography color="text.secondary" fontSize={12} sx={{letterSpacing:1.5,mb:1}}>PLANEJAMENTO OPERACIONAL</Typography><Typography variant="h4">{page===0?'O próximo dia começa aqui.':nav[page]}</Typography><Typography color="text.secondary" mt={1}>Pedidos, capacidade e equipe em uma mesma visão.</Typography></Box><Stack direction="row" alignItems="center" gap={1}><TextField type="date" size="small" label="Entrega prevista" slotProps={{inputLabel:{shrink:true}}} value={date} onChange={e=>setDate(e.target.value)}/><Button variant="contained" component="label">Importar planilha<input hidden type="file" accept=".xlsx" onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value=''}}/></Button></Stack></Stack>
<Stack direction={{xs:'column',sm:'row'}} gap={2} alignItems="center" justifyContent="space-between" sx={{mb:3}}><Alert severity={demo?'warning':'info'} sx={{flex:1}}>{demo?'Simulação: números fictícios, sem consulta ao banco.':'Dados reais são carregados por consulta da API ou arquivo JSON local. A importação XLSX identifica pedidos e rotas; PBs dependem do SYSEMP.'}</Alert><Button variant="outlined" onClick={()=>setPage(6)}>Configurar conexão</Button><FormControlLabel control={<Switch checked={demo} onChange={e=>setDemo(e.target.checked)}/>} label="Ver exemplos"/></Stack>{message&&<Alert onClose={()=>setMessage('')} sx={{mb:2}}>{message}</Alert>}
{(page===0||page===1)&&!demo&&<SysempPanel connection={connection} date={date} orders={unique}/>}
{page===6&&<SysempPanel connection={connection} date={date} orders={unique} settings/>}
{(page===0||page===1)&&demo&&<><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',lg:'repeat(4,1fr)'},gap:2,mb:4}}>{[['Rotas em planejamento',routes.length],['Pedidos previstos',routes.reduce((a,r)=>a+r.orders,0)],['PB previstos',routes.reduce((a,r)=>a+r.pb,0)],['Revisões de capacidade',routes.filter(r=>r.pb>capacity(r)||r.truck>truckMax).length]].map(([label,value])=><Paper key={label} sx={{p:3,border:'1px solid #e0e5db'}}><Typography fontSize={13} color="text.secondary">{label}</Typography><Typography variant="h3" fontWeight={700} mt={1}>{value}</Typography><Typography fontSize={11} color="text.secondary" mt={1}>Cenário demonstrativo</Typography></Paper>)}</Box><Stack direction="row" justifyContent="space-between" alignItems="center" mb={2}><Typography variant="h6">Pré-rotas e ocupação</Typography><Chip label="Revisão humana necessária" size="small"/></Stack><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'repeat(3,1fr)'},gap:2}}>{routes.map(r=><Paper key={r.id} sx={{p:3,border:'1px solid #e0e5db'}}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>ROTA {String(r.id).padStart(2,'0')}</Typography><Chip size="small" label={r.intensity} variant="outlined"/></Stack><Typography variant="h6" mt={1}>{r.name}</Typography><Typography color="text.secondary" fontSize={13} mb={3}>{r.driver} {r.fixed?'· Motorista fixo':''}</Typography><Stack direction="row" justifyContent="space-between"><Typography fontSize={13}>Ocupação estimada</Typography><Typography fontSize={13} fontWeight={700}>{r.pb} / {capacity(r)} PB</Typography></Stack><LinearProgress variant="determinate" value={Math.min(100,r.pb/capacity(r)*100)} color={r.pb>capacity(r)?'error':'primary'} sx={{height:7,borderRadius:8,my:1.5,bgcolor:'#e8ecdf'}}/><Typography fontSize={12} color="text.secondary">{r.truck} PB caminhão incluídos no total · {r.days} dia(s)</Typography><Divider sx={{my:2}}/><Stack direction="row" justifyContent="space-between"><Typography fontSize={13}>{r.orders} pedidos · {r.km} km de referência</Typography><Button size="small" onClick={()=>setSelected({...r})}>Revisar →</Button></Stack></Paper>)}</Box><Paper sx={{mt:3,p:3,bgcolor:'#e7eddd'}}><Typography fontWeight={750}>Operação dedicada · Bonini</Typography><Typography fontSize={14} mt={1}>Motorista exclusivo. Chegada ao CD às 13h, fechamento e posterior atendimento da blindadora. Alocação separada da rota 02 comum.</Typography></Paper></>}
{page===2&&<Paper sx={{p:3}}><Typography variant="h6">Conciliar listas de pedidos</Typography><Typography color="text.secondary" mb={2}>Cole um pedido por linha. Pontos e vírgulas internos serão removidos. Reentregas devem ser conferidas pela carga.</Typography><Stack direction={{xs:'column',md:'row'}} gap={2}><TextField fullWidth multiline minRows={7} label="Pedidos SYSEMP" value={left} onChange={e=>setLeft(e.target.value)}/><TextField fullWidth multiline minRows={7} label="Pedidos Cobli" value={right} onChange={e=>setRight(e.target.value)}/></Stack><Stack direction={{xs:'column',sm:'row'}} gap={2} mt={3}>{[['Em ambos',comp.match],['Faltam no Cobli',comp.missing],['Extras no Cobli',comp.extra]].map(([title,values])=><Box key={String(title)} sx={{flex:1,p:2,bgcolor:'#f4f5f0',borderRadius:2}}><Typography fontWeight={700}>{String(title)} · {(values as string[]).length}</Typography><Typography sx={{wordBreak:'break-word',mt:1}}>{(values as string[]).join(', ')||'—'}</Typography></Box>)}</Stack>{[left,right].some(x=>clean(x).some(v=>!/^\d+$/.test(v.clean)))&&<Alert severity="warning" sx={{mt:2}}>Há linhas inválidas; elas não entraram na comparação. Use somente números de pedidos, um por linha.</Alert>}</Paper>}
{page===3&&<Paper sx={{p:3}}><Typography variant="h6">Pedidos prontos para copiar</Typography>{rows.length>0&&<Alert severity="info" sx={{my:2}}>{fileName}: {rows.length} registros. Rotas informadas no arquivo: {importedRoutes.join(' · ')||'Coluna ROTA ausente ou vazia'}. Esses rótulos não confirmam carga montada no SYSEMP.</Alert>}{column&&<Stack direction={{xs:'column',sm:'row'}} gap={1} sx={{my:2}}><Button variant="outlined" onClick={()=>setPage(0)}>Ver consulta e conferir vínculos</Button><Button variant="contained" disabled={connection.busy||!connection.url||!connection.key||unique.length===0||unique.length>500||invalid.length>0} onClick={()=>{setPage(0);void connection.run('conferir',unique)}}>Buscar cargas dos {unique.length} pedidos</Button></Stack>}<Typography color="text.secondary" mb={3}>Remove pontuação de cada pedido e cria a lista separada por vírgulas.</Typography>{columns.length>0&&<TextField select fullWidth label="Coluna de pedidos" value={column} onChange={e=>{setColumn(e.target.value);setRaw(rows.map(r=>String(r[e.target.value]??'')).join('\n'))}} sx={{mb:2}}>{columns.map(c=><MenuItem key={c} value={c}>{c}</MenuItem>)}</TextField>}<TextField label="Um pedido por linha" fullWidth multiline minRows={6} value={raw} onChange={e=>setRaw(e.target.value)}/><Typography mt={2} fontSize={13}>{unique.length} pedidos únicos · {ids.length-unique.length} repetições removidas</Typography>{invalid.length>0&&<Alert severity="warning" sx={{my:2}}>Confira as linhas ignoradas: {invalid.map(x=>x.original).join(' | ')}</Alert>}<TextField fullWidth multiline label="Resultado" value={result} slotProps={{input:{readOnly:true}}} sx={{mt:2}}/><Button variant="contained" disabled={!result} sx={{mt:2}} onClick={()=>{navigator.clipboard.writeText(result).then(()=>setMessage('Pedidos copiados.')).catch(()=>setMessage('Selecione e copie o resultado manualmente.'))}}>Copiar pedidos</Button></Paper>}
{page===4&&<Paper sx={{p:3,overflowX:'auto'}}><Typography variant="h6" mb={2}>Simulação de alocação e motoristas fixos</Typography><Alert severity="info" sx={{mb:2}}>Alterações deste protótipo ficam somente nesta sessão. Intensidade operacional não mede fadiga.</Alert><Table><TableHead><TableRow>{['Rota','Motorista','Ciclo','Intensidade','Fixo'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{routes.map(r=><TableRow key={r.id}><TableCell>{r.id} · {r.name}</TableCell><TableCell><TextField size="small" value={r.driver} onChange={e=>setRoutes(routes.map(x=>x.id===r.id?{...x,driver:e.target.value}:x))}/></TableCell><TableCell>{r.days} dia(s)</TableCell><TableCell>{r.intensity}</TableCell><TableCell><Switch checked={r.fixed} onChange={e=>setRoutes(routes.map(x=>x.id===r.id?{...x,fixed:e.target.checked}:x))}/></TableCell></TableRow>)}</TableBody></Table></Paper>}
{page===5&&<Paper sx={{p:3}}><Typography variant="h6">Referências de capacidade</Typography><Alert severity="warning" sx={{my:2}}>Valores iniciais do POP. Cargas mistas e modelos repetidos exigem validação. Sem classificação por SKU, esta estimativa não libera carregamento.</Alert><Stack gap={2} maxWidth={450}>{[['PB variados',cap,setCap],['Total PB com caminhão',truckCap,setTruckCap],['Máximo PB caminhão',truckMax,setTruckMax]].map(([label,val,fn])=><TextField key={String(label)} label={String(label)} type="number" value={val as number} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>0)(fn as (v:number)=>void)(n)}}/>)}</Stack><Typography mt={3}>Datas divergentes devem ser sinalizadas, preservando o cadastro original. O calendário completo do POP ainda será parametrizado.</Typography></Paper>}
<Typography fontSize={11} color="text.secondary" mt={5}>ARENA / CENTRAL DE ROTAS · Consulta somente leitura · Alterações de simulação ficam nesta aba</Typography></Container></Box>
<Drawer anchor="right" open={!!selected} onClose={()=>setSelected(null)}>{selected&&<Box sx={{width:{xs:320,sm:440},p:4}}><Typography variant="h5" fontWeight={750}>Revisar rota {selected.id}</Typography><Typography color="text.secondary" mb={3}>{selected.name}</Typography><Stack spacing={3}><TextField label="Motorista" value={selected.driver} onChange={e=>setSelected({...selected,driver:e.target.value})}/><TextField label="Total de PB (inclui caminhão)" type="number" value={selected.pb} onChange={e=>setSelected({...selected,pb:Number(e.target.value)})}/><TextField label="PB caminhão" type="number" value={selected.truck} onChange={e=>setSelected({...selected,truck:Number(e.target.value)})}/><FormControlLabel control={<Switch checked={selected.fixed} onChange={e=>setSelected({...selected,fixed:e.target.checked})}/>} label="Motorista fixo"/><Alert severity="info">Simulação de carga. Distância e sequência não são recalculadas neste protótipo.</Alert><Button variant="contained" disabled={!Number.isFinite(selected.pb)||selected.pb<0||!Number.isFinite(selected.truck)||selected.truck<0||selected.truck>selected.pb} onClick={()=>{setRoutes(routes.map(r=>r.id===selected.id?selected:r));setSelected(null);setMessage('Simulação atualizada nesta sessão.')}}>Aplicar à simulação</Button><Button onClick={()=>setSelected(null)}>Fechar</Button></Stack></Box>}</Drawer></Box>
}

